set -e
cd /data/local/tmp/raven
export LD_LIBRARY_PATH=.
./pocket-tts "Warmup sentence for embedding cache." example.wav /data/local/tmp/raven/_warm.wav >/dev/null 2>&1 || true
echo "GS_RAVEN_BEGIN int8-1step-t0.70 short-001"
./pocket-tts 'Then came the Grasshopper.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.70 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.70 short-001"
echo "GS_RAVEN_END int8-1step-t0.70 short-001"
echo "GS_RAVEN_BEGIN int8-1step-t0.70 short-002"
./pocket-tts 'How it bloomed!' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.70 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.70 short-002"
echo "GS_RAVEN_END int8-1step-t0.70 short-002"
echo "GS_RAVEN_BEGIN int8-1step-t0.70 short-003"
./pocket-tts 'And what an odour!' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.70 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.70 short-003"
echo "GS_RAVEN_END int8-1step-t0.70 short-003"
echo "GS_RAVEN_BEGIN int8-1step-t0.70 median-001"
./pocket-tts 'Three famous jumpers were they, as everyone would say, when they all met together in the room.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.70 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.70 median-001"
echo "GS_RAVEN_END int8-1step-t0.70 median-001"
echo "GS_RAVEN_BEGIN int8-1step-t0.70 median-002"
./pocket-tts 'I jumped the highest; but in this world merit seldom meets its reward.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.70 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.70 median-002"
echo "GS_RAVEN_END int8-1step-t0.70 median-002"
echo "GS_RAVEN_BEGIN int8-1step-t0.70 dialogue-001"
./pocket-tts '“But how did the child get his feet wet?”' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.70 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.70 dialogue-001"
echo "GS_RAVEN_END int8-1step-t0.70 dialogue-001"
echo "GS_RAVEN_BEGIN int8-1step-t0.70 dialogue-002"
./pocket-tts '“Am I to hear a fairy tale?”' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.70 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.70 dialogue-002"
echo "GS_RAVEN_END int8-1step-t0.70 dialogue-002"
echo "GS_RAVEN_BEGIN int8-1step-t0.70 names-001"
./pocket-tts 'The Flea was the first to step forward.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.70 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.70 names-001"
echo "GS_RAVEN_END int8-1step-t0.70 names-001"
echo "GS_RAVEN_BEGIN int8-1step-t0.70 punctuation-001"
./pocket-tts 'I opened it instantly and read: I laughed and wept.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.70 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.70 punctuation-001"
echo "GS_RAVEN_END int8-1step-t0.70 punctuation-001"
echo "GS_RAVEN_BEGIN int8-1step-t0.20 short-001"
./pocket-tts 'Then came the Grasshopper.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.20 short-001"
echo "GS_RAVEN_END int8-1step-t0.20 short-001"
echo "GS_RAVEN_BEGIN int8-1step-t0.20 short-002"
./pocket-tts 'How it bloomed!' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.20 short-002"
echo "GS_RAVEN_END int8-1step-t0.20 short-002"
echo "GS_RAVEN_BEGIN int8-1step-t0.20 short-003"
./pocket-tts 'And what an odour!' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.20 short-003"
echo "GS_RAVEN_END int8-1step-t0.20 short-003"
echo "GS_RAVEN_BEGIN int8-1step-t0.20 median-001"
./pocket-tts 'Three famous jumpers were they, as everyone would say, when they all met together in the room.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.20 median-001"
echo "GS_RAVEN_END int8-1step-t0.20 median-001"
echo "GS_RAVEN_BEGIN int8-1step-t0.20 median-002"
./pocket-tts 'I jumped the highest; but in this world merit seldom meets its reward.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.20 median-002"
echo "GS_RAVEN_END int8-1step-t0.20 median-002"
echo "GS_RAVEN_BEGIN int8-1step-t0.20 dialogue-001"
./pocket-tts '“But how did the child get his feet wet?”' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.20 dialogue-001"
echo "GS_RAVEN_END int8-1step-t0.20 dialogue-001"
echo "GS_RAVEN_BEGIN int8-1step-t0.20 dialogue-002"
./pocket-tts '“Am I to hear a fairy tale?”' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.20 dialogue-002"
echo "GS_RAVEN_END int8-1step-t0.20 dialogue-002"
echo "GS_RAVEN_BEGIN int8-1step-t0.20 names-001"
./pocket-tts 'The Flea was the first to step forward.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.20 names-001"
echo "GS_RAVEN_END int8-1step-t0.20 names-001"
echo "GS_RAVEN_BEGIN int8-1step-t0.20 punctuation-001"
./pocket-tts 'I opened it instantly and read: I laughed and wept.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 1 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-1step-t0.20 punctuation-001"
echo "GS_RAVEN_END int8-1step-t0.20 punctuation-001"
echo "GS_RAVEN_BEGIN int8-4step-t0.20 short-001"
./pocket-tts 'Then came the Grasshopper.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 4 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-4step-t0.20 short-001"
echo "GS_RAVEN_END int8-4step-t0.20 short-001"
echo "GS_RAVEN_BEGIN int8-4step-t0.20 short-002"
./pocket-tts 'How it bloomed!' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 4 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-4step-t0.20 short-002"
echo "GS_RAVEN_END int8-4step-t0.20 short-002"
echo "GS_RAVEN_BEGIN int8-4step-t0.20 short-003"
./pocket-tts 'And what an odour!' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 4 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-4step-t0.20 short-003"
echo "GS_RAVEN_END int8-4step-t0.20 short-003"
echo "GS_RAVEN_BEGIN int8-4step-t0.20 median-001"
./pocket-tts 'Three famous jumpers were they, as everyone would say, when they all met together in the room.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 4 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-4step-t0.20 median-001"
echo "GS_RAVEN_END int8-4step-t0.20 median-001"
echo "GS_RAVEN_BEGIN int8-4step-t0.20 median-002"
./pocket-tts 'I jumped the highest; but in this world merit seldom meets its reward.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 4 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-4step-t0.20 median-002"
echo "GS_RAVEN_END int8-4step-t0.20 median-002"
echo "GS_RAVEN_BEGIN int8-4step-t0.20 dialogue-001"
./pocket-tts '“But how did the child get his feet wet?”' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 4 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-4step-t0.20 dialogue-001"
echo "GS_RAVEN_END int8-4step-t0.20 dialogue-001"
echo "GS_RAVEN_BEGIN int8-4step-t0.20 dialogue-002"
./pocket-tts '“Am I to hear a fairy tale?”' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 4 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-4step-t0.20 dialogue-002"
echo "GS_RAVEN_END int8-4step-t0.20 dialogue-002"
echo "GS_RAVEN_BEGIN int8-4step-t0.20 names-001"
./pocket-tts 'The Flea was the first to step forward.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 4 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-4step-t0.20 names-001"
echo "GS_RAVEN_END int8-4step-t0.20 names-001"
echo "GS_RAVEN_BEGIN int8-4step-t0.20 punctuation-001"
./pocket-tts 'I opened it instantly and read: I laughed and wept.' example.wav /data/local/tmp/raven/_out.wav --precision int8 --lsd-steps 4 --temperature 0.20 2>&1 || echo "GS_RAVEN_ERR int8-4step-t0.20 punctuation-001"
echo "GS_RAVEN_END int8-4step-t0.20 punctuation-001"
